name: Publish NPM Package

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Check if PR is a release
        id: check_release
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            // Check for label
            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number
            });
            const hasReleaseLabel = labels.some(label => label.name === 'release');

            // Check for title
            const titlePattern = /^Release \d+\.\d+\.\d+$/;
            const isReleaseTitle = titlePattern.test(pr.title);

            return hasReleaseLabel && isReleaseTitle;

      - name: Publish NPM Package
        if: steps.check_release.outputs.result == 'true'
        run: |
          npm ci
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
